openra-raclassic: 164->162

diff --git a/pkgs/games/openra-raclassic/Makefile.patch b/pkgs/games/openra-raclassic/Makefile.patch
--- a/pkgs/games/openra-raclassic/Makefile.patch
+++ b/pkgs/games/openra-raclassic/Makefile.patch
@@ -1,19 +1,25 @@
 diff --git a/Makefile b/Makefile
-index e637d82..4440f1d 100644
+index ea94401..a91dc32 100644
 --- a/Makefile
 +++ b/Makefile
-@@ -40,7 +40,6 @@ LUA_FILES = $(shell find mods/*/maps/* -iname '*.lua')
- PROJECT_DIRS = $(shell dirname $$(find . -iname "*.csproj" -not -path "$(ENGINE_DIRECTORY)/*"))
+@@ -37,11 +37,8 @@ PROJECT_DIRS = $(shell dirname $$(find . -iname "*.csproj" -not -path "$(ENGINE_
  
- engine:
+ check-sdk-scripts:
+ 	@awk '/\r$$/ { exit(1); }' mod.config || (printf "Invalid mod.config format: file must be saved using unix-style (CR, not CRLF) line endings.\n"; exit 1)
+-	@if [ ! -x "fetch-engine.sh" ] || [ ! -x "launch-dedicated.sh" ] || [ ! -x "launch-game.sh" ] || [ ! -x "utility.sh" ]; then \
++	@if [ ! -x "launch-dedicated.sh" ] || [ ! -x "launch-game.sh" ] || [ ! -x "utility.sh" ]; then \
+ 		echo "Required SDK scripts are not executable:"; \
+-		if [ ! -x "fetch-engine.sh" ]; then \
+-			echo "   fetch-engine.sh"; \
+-		fi; \
+ 		if [ ! -x "launch-dedicated.sh" ]; then \
+ 			echo "   launch-dedicated.sh"; \
+ 		fi; \
+@@ -95,7 +92,6 @@ check-variables:
+ 	fi
+ 
+ engine: check-variables check-sdk-scripts
 -	@./fetch-engine.sh || (printf "Unable to continue without engine files\n"; exit 1)
  	@cd $(ENGINE_DIRECTORY) && make core
  
  utility: engine
-@@ -91,4 +90,4 @@ check: utility stylecheck
- 
- test: utility
- 	@echo "Testing $(MOD_ID) mod MiniYAML..."
--	@MOD_SEARCH_PATHS="$(MOD_SEARCH_PATHS)" mono --debug "$(ENGINE_DIRECTORY)/OpenRA.Utility.exe" $(MOD_ID) --check-yaml
-\ No newline at end of file
-+	@MOD_SEARCH_PATHS="$(MOD_SEARCH_PATHS)" mono --debug "$(ENGINE_DIRECTORY)/OpenRA.Utility.exe" $(MOD_ID) --check-yaml
